# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'BookStorePro' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BookStorePro
  pod 'Alamofire', '~> 4.5'
end
